### PR TITLE
fix minor typo in README

### PR DESCRIPTION
**Pull request by bfallik**

### CODE REVIEW

**Comment by giuseppe** [comment]
LGTM, could you please sign your commit (`git commit --amend -s`) and push again?

**Comment by bfallik** [comment]
@giuseppe Sure. I submitted this edit from the github UI, which I guess doesn't support signing. Should be all set now.

**Review by giuseppe — APPROVED** [review]

**Comment by cgwalters** [comment]
Hello @bfallik there's a request to relicense this repository, please comment on https://github.com/containers/composefs/issues/344

**Comment by bfallik** [comment]
@cgwalters I approve the relicensing of my contribution

**Pull request merged**
