### PR TITLE
Start collecting Fedora review fixes

### PR DESCRIPTION
**Pull request by smooge**
- Take in fixes from reviwers to fix man page compression types
- Take in fixes from reviwers to move licenses to lib subpackage

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Looks sane to me but honestly I feel like keeping spec files upstream has generally just involved duplication and pain (e.g. how one can't use autochangelog in C9S) so it's easier to just keep these things downstream.

**Comment by smooge** [comment]
Understood and mostly agreed. I am not sure if this is 'helping' as I expect that if someone wanted this for SuSE or Mageia or CBL-Mariner they would need to make more changes. I will stop making PR's from other changes found in the review unless the change really fixes something missed before

**Comment by cgwalters** [comment]
OK, want to change this PR to just remove the spec file and hence go to one fewer source of truth?

**Comment by smooge** [comment]
Sorry I missed your message. I am going to talk with @alexlarsson on this as I think he was wanting the spec for CI or something. I will update PR when I figure that out.

**Comment by smooge** [comment]
I tested this MR against f38-qemu-developer-regular.x86_64.json and cs9-qemu-developer-regular.x86_64.json

**Comment by alexlarsson** [comment]
I think its nice to have a good spec file for now, so other distros have a sane start when they start packaging it. I agree that it is sort of a paint to keep it updated though.

I'll just merge this for now, and we can reconsider dropping it at a later date.

**Pull request merged**
